name: Build

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dist-all-packages:
    runs-on: ubuntu-latest

    # Add env vars for tests
    env:
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
      TEST_2_MNEMONIC: ${{ secrets.TEST_2_MNEMONIC }}
      TEST_NODE_MNEMONIC: ${{ secrets.TEST_NODE_MNEMONIC }}
      # IOTA Gas Station configuration for tests
      iotaNodeEndpoint: https://api.testnet.iota.cafe
      iotaFaucetEndpoint: https://faucet.testnet.iota.cafe
      iotaNetwork: testnet
      iotaCoinType: '4218'
      iotaGasStationEndpoint: http://localhost:9527
      iotaGasStationAuthToken: qEyCL6d9BKKFl/tfDGAKeGFkhUlf7FkqiGV7Xw4JUsI=
      iotaGasStationEnabled: 'true'
      iotaGasStationTimeoutMs: '10000'

    steps:
      # Get the code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Setup test environment (IOTA CLI + Gas Station)
      - name: Setup Engine Testing Environment
        uses: ./.github/actions/setup-test-environment
        with:
          test-mnemonic: ${{ secrets.TEST_MNEMONIC }}
          test-node-endpoint: ${{ env.iotaNodeEndpoint }}
          test-faucet-endpoint: ${{ env.iotaFaucetEndpoint }}
          gas-station-auth: ${{ env.iotaGasStationAuthToken }}

      # Run Lint and Dist
      - name: Run Lint and Dist
        run: |
          npm run lint
          npm run dist
